### ISSUE TITLE
toimg eror

### ISSUE THREAD

**Issue by techwiz37** [RC047/Kuhong-V4#16]
Error: spawn convert ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn convert',
  path: 'convert',
  spawnargs: [ 'webp:-', 'png:-' ]
}

**Comment by RC047** [comment]
Erorr karna update baileys,, jdi fitur yg ngirim gambar jdi erorr
